name: Weather Email Alert Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every  hours

jobs:
  send-alert:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install gspread oauth2client

      - name: Write credentials.json
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          echo "credentials.json written successfully"

      - name: Verify file and directory
        run: |
          echo "Working directory: $(pwd)"
          echo "Contents of credentials.json:"
          cat credentials.json

      - name: Run weather email alert script
        env:
          # Pass Google credentials path as env var or handle in script
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python weather_email_alert.py
