name: Weather Update Automation

on:
  schedule:
    - cron: '0 * * * *'  # This runs the action every hour (cron syntax)
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run_weather_script:
    runs-on: ubuntu-latest  # The environment to run the action in

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your code to the runner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your dependencies (you must have a requirements.txt)

      - name: Run the script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}  # Set your Google credentials securely
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # Store your API key securely in GitHub secrets
        run: |
          python weather_script.py  # Replace with the actual name of your script
