name: Weather Tracker Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs hourly

jobs:
  run-weather:
    runs-on: ubuntu-latest

    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install jq  # Install jq to manipulate JSON if needed

      - name: Write credentials.json
        shell: bash
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          echo "credentials.json written successfully"

      - name: Verify credentials.json file existence
        run: |
          ls -l
          cat credentials.json

      - name: Run script
        run: python weather_script.py
